"""New models

Revision ID: 00b3439ed2da
Revises: 3cf1a185f29c
Create Date: 2025-12-24 23:26:44.018760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b3439ed2da'
down_revision: Union[str, Sequence[str], None] = '3cf1a185f29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_id'), 'community', ['id'], unique=False)
    op.create_index(op.f('ix_community_name'), 'community', ['name'], unique=True)
    op.create_table('community_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MODERATOR', 'MEMBER', name='communityrole'), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'profile_name', name='uq_community_profile_name'),
    sa.UniqueConstraint('user_id', 'community_id', name='uq_user_community')
    )
    op.create_index('ix_community_profile_community_id', 'community_profile', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_profile_id'), 'community_profile', ['id'], unique=False)
    op.create_index(op.f('ix_community_profile_profile_name'), 'community_profile', ['profile_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_profile_profile_name'), table_name='community_profile')
    op.drop_index(op.f('ix_community_profile_id'), table_name='community_profile')
    op.drop_index('ix_community_profile_community_id', table_name='community_profile')
    op.drop_table('community_profile')
    op.drop_index(op.f('ix_community_name'), table_name='community')
    op.drop_index(op.f('ix_community_id'), table_name='community')
    op.drop_table('community')
    # ### end Alembic commands ###
